### ISSUE TITLE
Hactivate one day?

### ISSUE THREAD

**Issue by eglacias** [32Bites/hacktivate#3]
This is literally the first time I’ve seen anyone talk about actually supporting real offline activation. If you need any help developing such a thing I have an iPhone 6s Plus, and a back up one that I can use for testing.

 My critical need stems from the following: I had my activation data deleted, and Apple Corporation shut down their activation server for iOS 933,  leaving my phone completely locked out, and forcing me to upgrade.

 The day Apple Corporation goes tits up, such behavior will make these devices into garbage unnecessarily with such behavior. [ and believe me if our economic system collapses, they will disappear with no remorse or care]

I never want this to happen again, it seem to happen by them, by remote. Even the ability to find and back up our activation data so that we can put it back while we’re still jailbroken before we reboot  would have stopped me from losing that old jailbreak!

**Comment by 32Bites** [comment]
This relies on the Checkra1n jailbreak. Which supports 12.3+.

**Comment by eglacias** [comment]
I’m aware of all that. I left a message because it would be nice to get this to actually activate the phone fully one day, whereas bypassing iCloud lock leaves the phone not very functional, it’s only good for data recovery, And I was willing to help test that functionality if you ever decide to work on it :-)
