### ISSUE TITLE
Will we get Full hacktivation features one day?

### ISSUE THREAD

**Issue by eglacias** [32Bites/hacktivate#4]
I’m sure this is possible as you say in the original header for this project, for us to be able to hactivate again like back in iOS 4 days, activate a phone with the activation server closed such as is the case for any devices on iOS 9.3.3, the last complete off-line jailbreak which I was forced to upgrade from when Apple closed Their activation server for that version and deleted my activation data from remote!

**Comment by 32Bites** [comment]
It completely depends on the furthering developments of the jailbreaking community. I lack the expertise myself to reverse engineer the binaries, but if someone figures it out I will implement it as soon as possible.
